sudo: required
dist: bionic
language: go
go: "1.12"

branches:
  only:
  - master
  - /^v[0-9]/

jobs:
  include:
  - stage: Tests
    name: Build pack8s
    script: make
  - name: Unit tests
    script: make tests

  - stage: Build and Deploy
    name: Build and Deploy to GitHub
    if: tag IS present
    before_script: skip
    script: make release "VERSION=$TRAVIS_TAG"
    deploy:
      provider: releases
      api_key: "$GITHUB_TOKEN"
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file:
      - _out/*
      name: $TRAVIS_TAG
      on:
        tags: true
        branch: master
        repo: $TRAVIS_REPO_SLUG

#set up podman, varlink, ginkgo
before_install:
  - sudo apt -y  install software-properties-common
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt -y install podman libvarlink containernetworking-plugins
  - sudo groupadd podman
  - echo "d /run/podman 0750 root podman" | sudo tee /etc/tmpfiles.d/podman.conf
  - sudo cp travis_ci/io.podman.socket /etc/systemd/system/io.podman.socket
  - sudo systemctl daemon-reload
  - sudo rm -r /run/podman
  - sudo systemd-tmpfiles --create
  - sudo systemctl enable --now io.podman.socket
  - sudo systemctl restart io.podman.socket
  - sudo systemctl restart io.podman.service
  - sudo usermod -G podman -a $USER
  - sudo systemctl status io.podman.socket
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
